apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
        - name: bind9
          command:
            [
              "/bin/sh",
              "-c",
              "cd /var/cache/bind && /usr/sbin/named -g -u bind -c /etc/bind/named.conf",
            ]
          image: "ubuntu/bind9:latest"
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 853
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: named-config
              mountPath: /etc/bind/named.conf
              subPath: named.conf
            - name: bind9-volume
              mountPath: /etc/bind/zones
            - name: tsig-secret
              mountPath: /etc/bind/keys/tsig-key
              subPath: tsig-key
              readOnly: true
      volumes:
        - name: named-config
          configMap:
            name: bind9-named-conf
        - name: bind9-volume
          persistentVolumeClaim:
            claimName: bind9-nas-pvc
        - name: tsig-secret
          secret:
            secretName: bind9-tsig-secret
