version: "3.9"

services:
  k8s-api-lb:
    image: haproxy:2.9
    container_name: k8s-api-lb
    restart: unless-stopped
    ports:
      - "6443:6443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
