apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Repositories:
      - Homelab:
        - icon: si-github-#FFFFFF
          href: https://github.com/sujiththirumalaisamy/homelab
    - Cloud Services:
      - Cloudflare:
        - icon: cloudflare.png
          href: https://dash.cloudflare.com
      - Twingate:
        - icon: twingate.png
          href: https://sujithfraidy.twingate.com
    - Cloud Platforms:
      - Amazon Web Services:
        - icon: mdi-aws-#FF9900
          href: https://aws.amazon.com
      - CIVO:
        - icon: si-civo-#239DFF
          href: https://dashboard.civo.com
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: false
        cpu: false
        memory: false
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
  services.yaml: |
    - Networking:
        - TpLink:
            href: https://10.0.0.2:8043
            icon: omada.png
            description: omada-controller
            siteMonitor: https://10.0.0.2:8043
            widget:
                type: omada
                url: https://10.0.0.2:8043
                username: admin
                password: FraidyTheBot@1267
                site: homelab
                connectedAp: true
                activeUser: true
                alerts: true
                connectedGateways: true
                connectedSwitches: true
